package OperationsApp;


/**
* OperationsApp/Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operations.idl
* Tuesday, November 5, 2019 6:29:05 o'clock PM EST
*/

public interface Operations extends OperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Operations
