package OperationsApp;

/**
* OperationsApp/OperationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operations.idl
* Tuesday, November 5, 2019 6:29:05 o'clock PM EST
*/

public final class OperationsHolder implements org.omg.CORBA.portable.Streamable
{
  public OperationsApp.Operations value = null;

  public OperationsHolder ()
  {
  }

  public OperationsHolder (OperationsApp.Operations initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OperationsApp.OperationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OperationsApp.OperationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OperationsApp.OperationsHelper.type ();
  }

}
