package OperationsApp;


/**
* OperationsApp/OperationsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operations.idl
* Tuesday, November 5, 2019 6:29:05 o'clock PM EST
*/

abstract public class OperationsHelper
{
  private static String  _id = "IDL:OperationsApp/Operations:1.0";

  public static void insert (org.omg.CORBA.Any a, OperationsApp.Operations that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static OperationsApp.Operations extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (OperationsApp.OperationsHelper.id (), "Operations");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static OperationsApp.Operations read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OperationsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, OperationsApp.Operations value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static OperationsApp.Operations narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OperationsApp.Operations)
      return (OperationsApp.Operations)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OperationsApp._OperationsStub stub = new OperationsApp._OperationsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static OperationsApp.Operations unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OperationsApp.Operations)
      return (OperationsApp.Operations)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OperationsApp._OperationsStub stub = new OperationsApp._OperationsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
